### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getTitle' of undefined

### ISSUE THREAD

**Issue by mmcgilvery** [nwhetsell/ide-csound#3]
Every time I try to run the program this pops up.

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [ide-csound](https://github.com/nwhetsell/ide-csound) package 0.0.9

### Stack Trace

Uncaught TypeError: Cannot read property 'getTitle' of undefined

```
At /Users/lcukypawn/.atom/packages/ide-csound/lib/message-history-element.coffee:11

TypeError: Cannot read property 'getTitle' of undefined
    at /packages/ide-csound/lib/message-history-element.coffee:11:12)
    at TabView.module.exports.TabView.updateTitle (/app.asar/node_modules/tabs/lib/tab-view.js:310:27)
    at /app.asar/node_modules/tabs/lib/tab-view.js:36:12)
    at TabBarView.module.exports.TabBarView.addTabForItem (/app.asar/node_modules/tabs/lib/tab-bar-view.js:216:17)
    at /app.asar/node_modules/tabs/lib/tab-bar-view.js:146:14)
    at /app.asar/node_modules/tabs/lib/main.js:83:24
    at /app.asar/src/pane-container.js:95:16
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at PaneContainer.module.exports.PaneContainer.didAddPane (/app.asar/src/pane-container.js:308:27)
    at Pane.module.exports.Pane.setContainer (/app.asar/src/pane.js:131:26)
    at PaneAxis.module.exports.PaneAxis.addChild (/app.asar/src/pane-axis.js:145:13)
    at PaneAxis.module.exports.PaneAxis.insertChildAfter (/app.asar/src/pane-axis.js:216:19)
    at Pane.module.exports.Pane.split (/app.asar/src/pane.js:938:23)
    at Pane.module.exports.Pane.splitDown (/app.asar/src/pane.js:907:19)
    at Object.run (/packages/ide-csound/lib/ide-csound.coffee:50:36)
    at /packages/ide-csound/lib/ide-csound.coffee:39:82)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/app.asar/src/atom-environment.js:1179:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:312:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -1:04.7.0 core:select-all (input.hidden-input)
     -1:03.7.0 core:backspace (input.hidden-input)
     -0:57.9.0 core:select-all (input.hidden-input)
     -0:57.1.0 core:backspace (input.hidden-input)
     -0:51.8.0 core:select-all (input.hidden-input)
     -0:50.3.0 core:backspace (input.hidden-input)
     -0:11.4.0 ide-csound:run (div.package-readme.native-key-bindings)
```

### Non-Core Packages

```
atom-beautify 0.29.18 
atom-clock 0.1.6 
double-tag 0.8.0 
atom-json-editor 0.4.1 
atom-material-syntax 1.0.2 
atom-music 0.7.0 
busy-signal 1.3.0 
dictionary 0.5.0 
electron 1.6.6 
html-template-generator 0.3.0 
ide-csound 0.0.9 
intentions 1.1.2 
json-generator 0.1.15 
language-csound 0.2.0 
linter-csound 0.2.4 
rhyming-dictionary 0.3.2 
TinyRave 2.2.1 
web-accessibility-checker 0.1.4 
web-audio-api-snippets 1.3.0 
web-lookup 1.3.1 
web-midi-api-snippets 0.1.3 
```

**Comment by nwhetsell** [comment]
I’m not able to reproduce this.
